version: '3'

volumes:
  staticfiles:
  media:

services:
  yufuquant.api:
    build:
      context: .
      dockerfile: compose/prod/Dockerfile
    image: yufuquant_api
    container_name: yufuquant_api
    working_dir: /app
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - staticfiles:/app/staticfiles
      - media:/app/media
    env_file:
      - yufuquant.env
    expose:
      - "8000"
    command: /start.sh

  yufuquant.nginx:
    build:
      context: .
      dockerfile: compose/prod/nginx/Dockerfile
    image: yufuquant_nginx
    container_name: yufuquant_nginx
    depends_on:
      - yufuquant.api
    volumes:
      - staticfiles:/apps/yufuquant/staticfiles
      - media:/apps/yufuquant/media
      - ./frontend/dist:/apps/yufuquant/dist
    ports:
      - "8080:80"
      - "8443:443"